name: 'zendesk'
version: '1.0.0'

config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
on-run-start: '{{ fivetran_utils.empty_variable_warning("ticket_field_history_columns", "zendesk_ticket_field_history") }}'
models:
  zendesk:
    +schema: zendesk
    +materialized: table
    agent_work_time:
      +materialized: ephemeral
    intermediate:
      +schema: zendesk_intermediate
      +materialized: table
      int_zendesk__schedule_timezones:
        +materialized: ephemeral
      int_zendesk__schedule_holiday:
        +materialized: ephemeral
    reply_times:
      +materialized: ephemeral
    resolution_times:
      +materialized: ephemeral
    sla_policy:
      +schema: zendesk_intermediate
      +materialized: table
      reply_time:
        int_zendesk__commenter_reply_at:
          +materialized: ephemeral
    ticket_history:
      +schema: zendesk_intermediate
      +materialized: ephemeral
    unstructured:
      +schema: zendesk_unstructured
      +materialized: table
    utils:
      +materialized: ephemeral
    staging:
      +schema: zendesk_source
      +materialized: table
      tmp:
        +schema: view
vars:
  zendesk:
    ticket_field_history_columns: ['assignee_id', 'status', 'priority']
    ticket_field_history_updater_columns: []
    zendesk__ticket_passthrough_columns: []
    zendesk__user_passthrough_columns: []
    zendesk__organization_passthrough_columns: []
    zendesk_sources: []
    audit_log: "{{ source('zendesk', 'audit_log') }}"
    brand: "{{ source('zendesk', 'brand') }}"
    daylight_time: "{{ source('zendesk', 'daylight_time') }}"
    domain_name: "{{ source('zendesk', 'domain_name') }}"
    field_history: "{{ source('zendesk', 'ticket_field_history') }}"
    group: "{{ source('zendesk', 'group') }}"
    organization_tag: "{{ source('zendesk', 'organization_tag') }}"
    organization: "{{ source('zendesk', 'organization') }}"
    schedule_holiday: "{{ source('zendesk', 'schedule_holiday') }}"
    schedule: "{{ source('zendesk', 'schedule') }}"
    ticket_comment: "{{ source('zendesk', 'ticket_comment') }}"
    ticket_form_history: "{{ source('zendesk', 'ticket_form_history') }}"
    ticket_schedule: "{{ source('zendesk', 'ticket_schedule') }}"
    ticket_tag: "{{ source('zendesk', 'ticket_tag') }}"
    ticket: "{{ source('zendesk', 'ticket') }}"
    time_zone: "{{ source('zendesk', 'time_zone') }}"
    user_tag: "{{ source('zendesk', 'user_tag') }}"
    user: "{{ source('zendesk', 'user') }}"
    ticket_chat: "{{ source('zendesk', 'ticket_chat') }}"
    ticket_chat_event: "{{ source('zendesk', 'ticket_chat_event') }}"

    using_schedules: true
    using_domain_names: true
    using_user_tags: true
    using_ticket_form_history: true
    using_organization_tags: true

    ticket_field_history_extension_months: 0 # how long to extend a ticket's field history past its closure date
    ticket_field_history_timeframe_years: 50 # how far back to pull tickets' field histories. default is everything
