name: 'zendesk'
version: '0.16.0'


config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
on-run-start: '{{ fivetran_utils.empty_variable_warning("ticket_field_history_columns", "zendesk_ticket_field_history") }}'
models:
  zendesk:
    +schema: zendesk
    +materialized: table
    agent_work_time:
      +materialized: ephemeral
    intermediate:
      +schema: zendesk_intermediate
      +materialized: table
    reply_times:
      +materialized: ephemeral
    resolution_times:
      +materialized: ephemeral
    sla_policy:
      +schema: zendesk_intermediate
      +materialized: table
    ticket_history:
      +schema: zendesk_intermediate
      +materialized: ephemeral
    utils:
      +materialized: ephemeral
vars:
  zendesk:
    ticket_field_history_columns: ['assignee_id', 'status', 'priority']
    ticket_field_history_updater_columns: []
    group: "{{ ref('stg_zendesk__group') }}"
    brand: "{{ ref('stg_zendesk__brand') }}"
    domain_name: "{{ ref('stg_zendesk__domain_name') }}"
    organization_tag: "{{ ref('stg_zendesk__organization_tag') }}"
    organization: "{{ ref('stg_zendesk__organization') }}"
    schedule: "{{ ref('stg_zendesk__schedule') }}"
    schedule_holiday: "{{ ref('stg_zendesk__schedule_holiday') }}"
    ticket: "{{ ref('stg_zendesk__ticket') }}"
    ticket_form_history: "{{ ref('stg_zendesk__ticket_form_history') }}"
    ticket_comment: "{{ ref('stg_zendesk__ticket_comment') }}"
    field_history: "{{ ref('stg_zendesk__ticket_field_history') }}"
    ticket_schedule: "{{ ref('stg_zendesk__ticket_schedule') }}"
    ticket_tag: "{{ ref('stg_zendesk__ticket_tag') }}"
    user_tag: "{{ ref('stg_zendesk__user_tag') }}"
    user: "{{ ref('stg_zendesk__user') }}"
    daylight_time: "{{ ref('stg_zendesk__daylight_time') }}"
    time_zone: "{{ ref('stg_zendesk__time_zone') }}"
    using_schedules: true
    using_domain_names: true
    using_user_tags: true
    using_ticket_form_history: true
    using_organization_tags: true

    ticket_field_history_extension_months: 0 # how long to extend a ticket's field history past its closure date
    ticket_field_history_timeframe_years: 50 # how far back to pull tickets' field histories. default is everything
